### ISSUE TITLE
This is a pure non-working copy of bibox api

### ISSUE THREAD

**Issue by yukseljunk** [BiboxEurope/REST-API-demos#1]
Have anyone tested if this is working at all? I got always 400 bad request

**Comment by BiboxEurope** [comment]
Hello,&nbsp;


We truly apologize for the inconvenience caused. Our tech team has updated the API docs and it can now be found on git hub at&nbsp;https://github.com/BiboxEurope/API_Docs_en/wiki/REST_Request_Response&nbsp;


All best,


BiboxEurope team
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by yukseljunk** [comment]
Thank you
